import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import SubjectArtwork from '../components/SubjectArtwork'
import LearningIcon from '../components/LearningIcon'
import useLearningProgress from '../utils/useLearningProgress'

const subjects = [
  ['Mind & society', 'Psychology', 'Understand how people think, feel, and behave.', '01'],
  ['Science & nature', 'Astronomy', 'Explore the stars, galaxies, and our place in space.', '02'],
  ['Arts & ideas', 'Creative writing', 'Learn to shape ideas into stories worth reading.', '03'],
  ['History & culture', 'World history', 'Connect the people and ideas that shaped our world.', '04'],
]
export default function LearningHome() {
  const { tracks, customStatus } = useLearningProgress()
  const [subject, setSubject] = useState('')
  const navigate = useNavigate()
  const personal = tracks.filter(t => t.to.startsWith('/roadmaps/'))
  const active = [...personal, ...tracks.filter(t => !t.to.startsWith('/roadmaps/'))].filter(t => t.done + t.started > 0 && t.done < t.total)
  const current = active[0]
  const completed = tracks.reduce((total, t) => total + t.done, 0)
  const start = value => navigate(`/roadmaps?subject=${encodeURIComponent(value.trim())}`)
  const renderTrack = (track, index) => <Link className="subject-book saved-path-book" key={track.to} to={track.to}>
    <span className="subject-book-category">{track.to.startsWith('/roadmaps/') ? 'Your personal path' : 'Technical collection'}<LearningIcon name={track.icon || (track.to === '/ai-interview' ? 'interview' : track.to.slice(1))} size={19} /></span>
    <strong>{track.title}</strong><span className="subject-book-number" aria-hidden="true">{String(index + 1).padStart(2, '0')}</span><p>{track.description}</p>
    <span className="book-progress"><span>{track.done} of {track.total} {track.unit} completed</span><progress value={track.done} max={track.total || 1} aria-label={`${track.title} completion`} /></span><span className="subject-book-action">{track.done + track.started ? 'Open your path' : 'Explore this path'}<LearningIcon name="arrow" size={17} /></span>
  </Link>
  return <div className="learning-overview universal-library">
    <header className="discovery-heading"><div><span className="learning-eyebrow">LEARNING LAB · YOUR SPACE TO EXPLORE</span><h1>Follow your curiosity.</h1><p>Choose a subject. Find a clear path. Learn through thoughtful, readable lessons.</p></div><Link to="/stats" className="discovery-progress"><strong>{completed}</strong><span>items completed <LearningIcon name="arrow" size={14} /></span></Link></header>
    <section className="subject-launcher" aria-labelledby="subject-heading"><div className="subject-launcher-copy"><span className="learning-eyebrow">FROM A QUESTION TO A LEARNING PATH</span><h2 id="subject-heading">What would you like to understand?</h2><form onSubmit={e => { e.preventDefault(); start(subject) }}><label className="subject-input-label" htmlFor="learning-subject">What do you want to learn?</label><input id="learning-subject" value={subject} onChange={e => setSubject(e.target.value)} placeholder="e.g. Psychology or world history" required minLength={2} maxLength={160} /><button type="submit" disabled={subject.trim().length < 2}>Build my path <LearningIcon name="arrow" size={17} /></button></form><div className="subject-examples"><span>Try</span>{['Psychology', 'World history', 'Photography', 'Artificial intelligence'].map(s => <button key={s} onClick={() => start(s)}>{s}</button>)}</div></div><ol className="reading-path-preview" aria-label="How learning works"><li><span>01</span><div><strong>Find your foundations</strong><small>A roadmap matched to your level</small></div></li><li><span>02</span><div><strong>Read to understand</strong><small>Focused lessons, examples, and ideas</small></div></li><li><span>03</span><div><strong>Make it yours</strong><small>Reflect, review, and track your progress</small></div></li></ol></section>
    {current && <Link to={current.next || current.to} className="universal-continue"><span className="universal-continue-icon"><LearningIcon name="blogs" size={23} /></span><div><span className="learning-eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>{current.title}</h2><p>{current.done} of {current.total} {current.unit} completed</p></div><span>Continue learning <LearningIcon name="arrow" size={18} /></span></Link>}
    <section aria-labelledby="personal-paths-heading"><div className="learning-section-title"><h2 id="personal-paths-heading">Your learning paths <span className="apple-count">{personal.length}</span></h2><Link to="/roadmaps">Manage roadmaps ↗</Link></div>{customStatus === 'loading' && <p role="status">Loading your learning paths…</p>}{customStatus === 'error' && <p className="learning-note" role="status">Custom roadmap progress could not be refreshed. <Link to="/roadmaps">Open your roadmaps</Link> to try again.</p>}{personal.length ? <div className="subject-shelf saved-path-shelf">{personal.map(renderTrack)}</div> : customStatus === 'ready' && <div className="personal-paths-empty"><span className="empty-path-mark" aria-hidden="true"><LearningIcon name="blogs" size={28} /></span><div><h3>Your first path starts with a subject.</h3><p>Build a path above, or explore the collections below. Your saved paths will appear here.</p><Link to="/roadmaps">Create a roadmap <LearningIcon name="arrow" size={17} /></Link></div></div>}</section>
    <section aria-labelledby="explore-heading"><div className="learning-section-title"><div><h2 id="explore-heading">A world of things to learn</h2><p>Starting points for your next personal roadmap.</p></div><Link to="/roadmaps">Choose your own subject ↗</Link></div><div className="subject-shelf">{subjects.map(([category, title, description, number]) => <Link key={title} to={`/roadmaps?subject=${encodeURIComponent(title)}`} className="subject-book"><span className="subject-book-category">{category}</span><strong>{title}</strong><SubjectArtwork index={Number(number) - 1} /><span className="subject-book-number" aria-hidden="true">{number}</span><p>{description}</p><span className="subject-book-action">Create a path <LearningIcon name="arrow" size={17} /></span></Link>)}</div></section>
    <section id="starter-paths"><div className="learning-section-title"><div><h2>Explore our technical collection</h2><p>Existing structured paths for coding, AI, and software engineering.</p></div></div><div className="subject-shelf saved-path-shelf">{tracks.filter(t => !t.to.startsWith('/roadmaps/')).map(renderTrack)}<Link className="subject-book practice-book" to="/practice"><span className="subject-book-category">PUT IT INTO WORDS<LearningIcon name="interview" size={19} /></span><strong>Interview practice</strong><p>Rehearse your answers, reflect on your approach, and build confidence for your next conversation.</p><span className="subject-book-action">Open interview practice<LearningIcon name="arrow" size={17} /></span></Link></div></section>
    <Link className="reading-library-callout" to="/blogs"><span className="reading-library-emblem" aria-hidden="true"><LearningIcon name="blogs" size={48} /></span><div><span className="learning-eyebrow">COLLECT IDEAS. COME BACK TO THEM.</span><h2>Your reading library</h2><p>Saved lessons and familiar ideas, ready for another look.</p><span className="reading-library-action">Open your library <LearningIcon name="arrow" size={18} /></span></div></Link>
  </div>
}
